### ISSUE TITLE
how can i change my api key?

### ISSUE THREAD

**Issue by MinHieu2006** [flashvayne/chatgpt-spring-boot-starter#11]
I follow your tutorial , but i don't know where is my application.yml. How to fix that?
Thanks!

**Comment by flashvayne** [comment]
Hi, You should find your application.yml in your own project which needs to use [chatgpt-spring-boot-starter].
Then you can chenge the api key in application.yml, just like the demo project [demo-chatgpt-spring-boot-starter](https://github.com/flashvayne/demo-chatgpt-spring-boot-starter)
