### ISSUE TITLE
额，是不是没给multichat自动配置

### ISSUE THREAD

**Issue by StarCode000** [flashvayne/chatgpt-spring-boot-starter#13]
就是说，我在application.yaml里面配置的max_tokens和temperature好像没起作用，全都用的是默认值：

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
![Snipaste_2023-03-30_22-34-10](https://user-images.githubusercontent.com/59649631/228872702-8772ff80-c927-470b-b38f-ffbfac637e60.png)
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
![Snipaste_2023-03-30_22-40-53](https://user-images.githubusercontent.com/59649631/228872714-65aaf529-ae4f-4cf0-9550-a934068c2537.png)

**Comment by flashvayne** [comment]
MultiChat should be configured using chatgpt.multi.xxxx as below.
```
chatgpt:
  api-key: sk-xxxxxxx
  multi:
    temperature: 0.5
```
Please refer to the configuration of demo project.
https://github.com/flashvayne/demo-chatgpt-spring-boot-starter/blob/master/src/main/resources/application.yml#L26

**Comment by StarCode000** [comment]
了解了
