### ISSUE TITLE
中国国内这个接口被墙，这个包还能用吗

### ISSUE THREAD

**Issue by 12915494174** [flashvayne/chatgpt-spring-boot-starter#4]
中国国内现在这个接口被墙，我直接导入到maven发送请求一直显示连接超时，这个问题该怎么解决？

**Comment by zdzhai** [comment]
我是一直访问不到，一直404，检查了好多次也没发现错误，debug发现压根就没进controller，请问大佬知道原因吗

**Comment by zdzhai** [comment]
> 中国国内现在这个接口被墙，我直接导入到maven发送请求一直显示连接超时，这个问题该怎么解决？

我是一直访问不到，一直404，检查了好多次也没发现错误，debug发现压根就没进controller，请问大佬知道原因吗

**Comment by zdzhai** [comment]
> 中国国内现在这个接口被墙，我直接导入到maven发送请求一直显示连接超时，这个问题该怎么解决？

我也出现了这样的问题

**Comment by flashvayne** [comment]
If your network is not able to access OpenAi Api, the starter can not work.
It is recommended to deploy the application to the server which can access OpenAi.
