### ISSUE TITLE
ajax能调通OpenAi的接口，也能访问外网，但是jar运行该项目会显示链接超时

### ISSUE THREAD

**Issue by longshao9543** [flashvayne/chatgpt-spring-boot-starter#7]
org.springframework.web.client.ResourceAccessException: I/O error on POST request for "https://api.openai.com/v1/completions": Connection timed out: connect; nested exception is java.net.ConnectException: Connection timed out: connect
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:785) ~[spring-web-5.3.19.jar:5.3.19]

**Comment by flashvayne** [comment]
It seems your jar application can not access openai. 
 I guess that Ajax accesses openai using the browser proxy, but your jar application does not use it.
